
version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Version information
          command: cargo --version
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - run:
          name: Print the Current Time
          command: date
